import Link from 'next/link';
import type { ScanRow } from '@/lib/types';
const fmt=(v:number|null,d=2)=>v==null?'N/A':v.toFixed(d);
const decisionClass=(d:string)=>d==='BUY'?'buy':d==='BUY RETEST'?'buyretest':d==='TEST BUY'?'testbuy':d==='DO NOT CHASE'?'nochase':d==='EXIT'?'exit':'watch';
export function ScanTable({rows}:{rows:ScanRow[]}){return <>
  <div className="toolbar"><div className="tabs"><button className="tab active">All</button><button className="tab">BUY</button><button className="tab">BUY RETEST</button><button className="tab">TEST BUY</button><button className="tab">WATCH</button></div><div className="dataStamp">EOD validated · 15:45 ICT</div></div>
  <div className="tableWrap"><table className="scanTable"><thead><tr><th>Mã</th><th>Điểm tổng</th><th>Tín hiệu chính</th><th>Tin tức nổi bật</th><th>Entry Zone</th><th>Stop</th><th>Stop Distance</th><th>1R</th><th>2R</th><th>3R</th><th>Decision</th><th>Invalidation</th></tr></thead><tbody>
  {rows.map(r=><tr key={r.symbol}><td><Link className="symbol" href={`/stocks/${r.symbol}`}>{r.symbol}</Link><div className="muted">{fmt(r.close,2)}</div></td><td><span className="score">{r.flow_score==null?'N/A':`${r.flow_score.toFixed(1)}%`}</span><div className="muted">{r.flow_label}</div></td><td className="signal">{r.main_signal}</td><td className="signal muted">{r.headline_news||'—'}</td><td>{r.entry_low==null?'N/A':`${fmt(r.entry_low)}–${fmt(r.entry_high)}`}</td><td className="num">{fmt(r.stop_price)}</td><td className="num">{r.stop_distance_pct==null?'N/A':`${fmt(r.stop_distance_pct,1)}%`}</td><td className="num">{fmt(r.one_r)}</td><td className="num">{fmt(r.two_r)}</td><td className="num">{fmt(r.three_r)}</td><td className="decision"><span className={`status ${decisionClass(r.decision)}`}>{r.decision}</span></td><td className="signal">{r.invalidation}</td></tr>)}
  </tbody></table></div></>}
